# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: |
    #cd /tmp 
    #sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash 
    NVM_DIR="/Users/runner/.nvm"
    NODE_VERSION="14.1.0"
    echo "*******************install node and npm"
    #source $NVM_DIR/nvm.sh &&\
    $NVM_DIR/nvm.sh install v$NODE_VERSION 
    $NVM_DIR/nvm.sh alias default $NODE_VERSION 
    $NVM_DIR/nvm.sh use default 
    echo " *************************** version de node" 
    node --version 
    echo " *************************** cd versions" 
    ls ~/.nvm/versions/node
    #sudo printenv

  displayName: 'npm install and build'
