# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: |
    #echo "desinstalando nvn instalado" 
    #nvm --version
    #npm uninstall -g nvm
    #rm -rf ~/.nvm
    #rm -rf ~/.npm
    #rm -rf ~/.bower
    echo "listar verificando nvm" 
    sudo pwd 
    echo " ********************* version de node" 
    node --version
    echo " ***version de npm"      
    npm -v
    echo "listar nvm"
    sudo ls ~/.nvm
    echo "ruta de : ~/.nvm"
    cd ~/.nvm
    pwd
    sudo ls /Users/runner/runners/2.166.4/work/1/s
- script: |
    #cd /tmp
    #sudo mkdir /Users/runner/nvm 
    #sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash 
    NVM_DIR="/usr/local/nvm"
    NODE_VERSION="10.19.0"
    echo "install node and npm"
    source $NVM_DIR/nvm.sh &&\
    nvm install $NODE_VERSION &&\
    nvm alias default $NODE_VERSION &&\
    nvm use default &&\
    ls /tmp

  displayName: 'npm install and build'
