# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.19'
  displayName: 'Instalando Node.js'

- script: |
    node --version
    npm install
    npm run build
    node --version
    npm --version
- script: |
    cd /tmp &&\
    curl https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh  &&\
    ls /tmp

  displayName: 'npm install and build'
