
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8'
  displayName: 'Instalando Node.js'

- script: |
    node --version
    npm install
    npm run build
    node --version
    npm --version
- script: |
    echo "hola mundo p" 
    cd /tmp   
    sudo mkdir /usr/local/nvm 
    echo "curl" 
    sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash 
    echo "listando" 
    sudo touch /usr/local/nvm/prueba.txt
    ls /usr/local/nvm 
    echo "variables de entorno"
    NVM_DIR="/usr/local/nvm"
    NODE_VERSION="10.19.0"
    echo "install node and npm"
    source $NVM_DIR/nvm.sh &&\
    nvm install $NODE_VERSION &&\
    nvm alias default $NODE_VERSION &&\
    nvm use default &&\
    ls /tmp

  displayName: 'npm install and build'
