# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: |
    echo "listar nvn instalado" 
    npm uninstall -g nvm
    sudo ls /Users/runner/.nvm
    sudo nvm use system
    sudo npm uninstall -g a_module
    echo "version de node" 
    node --version
    echo "version de npm" 
    npm install
    npm run build
    node --version
    npm --version
- script: |
    echo "hola mundo p" 
    cd /tmp   
    sudo mkdir /usr/local/nvm 
    echo "curl" 
    sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash 
    echo "listando" 
    sudo touch /usr/local/nvm/prueba.txt
    ls /usr/local/nvm 
    echo "variables de entorno"
    NVM_DIR="/usr/local/nvm"
    NODE_VERSION="10.19.0"
    echo "install node and npm"
    source $NVM_DIR/nvm.sh &&\
    nvm install $NODE_VERSION &&\
    nvm alias default $NODE_VERSION &&\
    nvm use default &&\
    ls /tmp

  displayName: 'npm install and build'
